### ISSUE TITLE
Modify behaviour to accommodate search box added by core in 1.24.0

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/filter_perms#14]
It looks like we are about to get a core search box on the permissions page in https://github.com/backdrop/backdrop-issues/issues/980.

This is a placeholder issue to alter out the search box provided by core (once it gets added), so that people using this module can have a more seamless user experience. :)

**Comment by yorkshire-pudding** [comment]
I'm not going to just remove the core search box as I really like it and think it is great.  I'm working on an approach that would allow users to make use of both filters in a non-clunky way whilst recognising that they need to use Filter Permissions first if `max_input_vars` might be a an issue.

**Comment by yorkshire-pudding** [comment]
There is a draft [PR](https://github.com/backdrop-contrib/filter_perms/pull/17) that alters the module to work better alongside the new core functionality.

@bugfolder , in particular, I would appreciate your feedback as someone who uses this on a large site.

This does not yet have the new dependency to allow it to be tested using a [patch](https://github.com/backdrop/backdrop/pull/4292.diff) for the core issue.

**Comment by bugfolder** [comment]
OK, I've tested on my local big site (19.5K permissions!) with 1.24.0-preview with the old and new versions of Filter Perms. Of course, when viewing the full page, I got the warning about `max_input_vars`, as expected.

I was puzzled that the core search filter disappeared when the page was too big, but it showed up if I was only looking at a single role (hence no warning). And then I saw in the code of the PR that this is intentional. I think the behavior would be confusing in this edge case. The problem with a big matrix happens at saving, and you've already (and properly) removed the Save button; but I think you should still allow people to use the core filter on an over-sized page if they so choose, if, for example, all they want to see is "what do all the roles have for permissions that have the word "image" in them?"

So I would suggest keeping the core test search visible even if the page can't be saved.

A small UI thing (feel free to ignore); it seemed a bit odd to have nice verbal explanations of the FP selectors but the core filter has no words of help text. The spare-ness of the core field is consistent with how it's used elsewhere (like the modules page) when it's all by itself, so I wouldn't advocate for changing core. But I wonder if FP could add some words explaining the differences and visually consolidate the controls. We now have two fieldset blocks, both called "Filter" something. Seems cleaner to have a single fieldset titled "Filters" allowing you to "Filter by Role", "Filter by Module", or "Filter by Text". (Implemented with some judicious application of `hook_form_alter()`).

**Comment by yorkshire-pudding** [comment]
> I was puzzled that the core search filter disappeared when the page was too big, but it showed up if I was only looking at a single role (hence no warning). And then I saw in the code of the PR that this is intentional. I think the behavior would be confusing in this edge case. The problem with a big matrix happens at saving, and you've already (and properly) removed the Save button; but I think you should still allow people to use the core filter on an over-sized page if they so choose, if, for example, all they want to see is "what do all the roles have for permissions that have the word "image" in them?"
> 
> So I would suggest keeping the core test search visible even if the page can't be saved.

I understand this concern, but the messaging gets complicated when you then have to explain that they can only filter using filter permissions; also what if they use that filter to check but then decide that something need changing? They have to then reapply the filters using filter permissions before they can amend.

If you can suggest some wording that works, I'm happy to reconsider that.

> A small UI thing (feel free to ignore); it seemed a bit odd to have nice verbal explanations of the FP selectors but the core filter has no words of help text. The spare-ness of the core field is consistent with how it's used elsewhere (like the modules page) when it's all by itself, so I wouldn't advocate for changing core. But I wonder if FP could add some words explaining the differences and visually consolidate the controls. We now have two fieldset blocks, both called "Filter" something. Seems cleaner to have a single fieldset titled "Filters" allowing you to "Filter by Role", "Filter by Module", or "Filter by Text". (Implemented with some judicious application of `hook_form_alter()`).

I did look at joining them up but they are separate forms. FP basically:

1. Changes the menu item to a new page callback
2. new callback outputs FP form and modified original form
3. original form is modified to filter using session variable from FP form
4. Page is reloaded when FP filters are applied

It would not be possible (I think) to inject the FP form elements into the existing form as FP has its own submit button that I have relabelled as apply since I relabelled the fieldset (it was Filter Permissions). The core search is within the main form.

It would be very confusing to have different filters that work in different ways in the same container:

- text acts instantly
- multi-select boxes need to be applied and page reloaded
- Reset reloads page but only clears text search; you have to manually select all roles/modules to clear the FP filters.

I quickly looked at adding some text into the core search field container but:

1.  It's not a fieldset so can't add description at the top as a property of fieldset
2. Trying to add it to the search field looked terrible

As I say, this was a quick look but I didn't pursue it as I didn't have time.  It could be possible to add a field label to core and also change the labels for FP filters, but is that still a good idea if they're not aligned?

They're not both called Filter, FP is trying to make clear that it is separate. Basically, you only need FP now if `max_input_vars` applies AND you need to modify more than one role at a time. If you use it on a site that doesn't need it and where no filters are active (whether selected manually or applied from the URL from role page/module page), then the FP fieldset is collapsed.

**Comment by bugfolder** [comment]
Makes sense, thanks for the detailed explanation.

There is a use case for a FP-like thing even when `max_input_vars` isn't an issue, which is simply to be able to work with permissions and not have to wait for the long load times of the whole matrix. But Role Listings (single-role permissions pages) plus the new core filter will allow that to be addressed.

**Comment by yorkshire-pudding** [comment]
> There is a use case for a FP-like thing even when `max_input_vars` isn't an issue, which is simply to be able to work with permissions and not have to wait for the long load times of the rull matrix. But Role Listings (single-role permissions pages) plus the new core filter will allow that to be addressed.

Good point. I should work that into the revised read me.
